const recepieactiontype = {
    USER_FETCH_DATA:'USER_FETCH_DATA',
    ADMIN_FETCH_DATA: 'ADMIN_FETCH_DATA',
    INVALIDC:'INVALIDC',
    USERVALID:'USERVALID',
    USERLOGIN:'USERLOGIN',
    ADMINVALID:'ADMINVALID',
    ADMINLOGIN:'ADMINLOGIN',
    ADMININVALIDC:'ADMININVALIDC',
    USERINVALIDC:'USERINVALIDC',
    USERADDCART:'USERADDCART'
}
export default recepieactiontype;